#!/usr/bin/env bash
# bid-app 容器 entrypoint
# 参考 IMPLEMENTATION_SPEC §17.1 §17.2 D-O
# 顺序:导出 cron env -> 等 postgres 可连 -> 同步执行 alembic upgrade head -> exec supervisord
set -euo pipefail

# set -u 下未定义环境变量会让 eval 直接 abort。给非密钥字段补默认值,
# 防止用户精简 .env 删掉这些行后 entrypoint 启动失败(REVIEW-4 🟡 nit)。
# 密钥字段(POSTGRES_PASSWORD / BID_APP_MASTER_KEY 等)不补默认 — 缺失就该立刻挂。
: "${POSTGRES_HOST:=postgres}"
: "${POSTGRES_PORT:=5432}"
: "${BACKUPS_DIR:=/var/lib/bid-app/backups}"
: "${TZ:=Asia/Shanghai}"

# 把当前环境变量写到 /etc/bid-app.env(给 cron 任务用,cron 默认无环境)
{
  echo "# auto-generated by entrypoint, do not edit"
  for v in POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB POSTGRES_HOST POSTGRES_PORT \
           BACKUPS_DIR TZ; do
    eval "echo export $v=\\\"\$$v\\\""
  done
} > /etc/bid-app.env
chmod 600 /etc/bid-app.env

# 等 postgres 真正可连(防止 healthcheck 还没刷)
echo "[entrypoint] waiting for postgres at ${POSTGRES_HOST}:${POSTGRES_PORT}..."
for i in $(seq 1 60); do
  if PGPASSWORD="$POSTGRES_PASSWORD" pg_isready -h "$POSTGRES_HOST" \
       -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q; then
    echo "[entrypoint] postgres ready (took ${i}s)"
    break
  fi
  if [ "$i" -eq 60 ]; then
    echo "[entrypoint] postgres not ready after 120s, aborting" >&2
    exit 1
  fi
  sleep 2
done

# DB Migration 同步执行(D-O:必须在 supervisord 拉起 uvicorn / arq 之前完成)
echo "[entrypoint] alembic upgrade head"
cd /app/backend
/app/backend/.venv/bin/python -m alembic -c /app/backend/alembic.ini upgrade head

# cron 由 supervisord [program:cron] 接管(`/usr/sbin/cron -f` 前台运行),
# 这里不再 service cron start,避免双进程争抢 pidfile。

echo "[entrypoint] starting supervisord"
exec "$@"
